/* Generated by the Nim Compiler v1.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var NTI1172041 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1172053 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1172049 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1166045 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI1325043 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1171808 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1172086 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI1166014 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI1166016 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI1172081 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI1172017 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1172019 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1172033 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1172037 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI1172037 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1172037.node = NNI1172037;
var NNI1172033 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1172033.node = NNI1172033;
var NNI1172019 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1172019.node = NNI1172019;
NTI1172081.base = NTI1172017;
NTI1172086.base = NTI1172017;
var NNI1172017 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI1172081, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI1166016, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI1166014, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI1166014, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI1172086, name: "up", sons: null}]};
NTI1172017.node = NNI1172017;
var NNI1171808 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1171808.node = NNI1171808;
NTI1172017.base = NTI1171808;
NTI1172019.base = NTI1172017;
NTI1172033.base = NTI1172019;
NTI1172037.base = NTI1172033;
var NNI1325043 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI1166016, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI1166045, name: "Field1", sons: null}]};
NTI1325043.node = NNI1325043;
var NNI1172049 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1172049.node = NNI1172049;
NTI1172049.base = NTI1172019;
var NNI1172053 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1172053.node = NNI1172053;
NTI1172053.base = NTI1172019;
var NNI1172041 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1172041.node = NNI1172041;
NTI1172041.base = NTI1172019;
function makeNimstrLit(c_1390062) {
      var ln = c_1390062.length;
  var result = new Array(ln);
  for (var i = 0; i < ln; ++i) {
    result[i] = c_1390062.charCodeAt(i);
  }
  return result;
  

  
}
function arrayConstr(len_1415067, value_1415068, typ_1415069) {
        var result = new Array(len_1415067);
    for (var i = 0; i < len_1415067; ++i) result[i] = nimCopy(null, value_1415068, typ_1415069);
    return result;
  

  
}
function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);
function nimCopy(dest_1405023, src_1405024, ti_1405025) {
  var result_1410219 = null;

    switch (ti_1405025.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(is_fat_pointer_1400401(ti_1405025))) {
      result_1410219 = src_1405024;
      }
      else {
        result_1410219 = [src_1405024[0], src_1405024[1]];
      }
      
      break;
    case 19:
            if (dest_1405023 === null || dest_1405023 === undefined) {
        dest_1405023 = {};
      }
      else {
        for (var key in dest_1405023) { delete dest_1405023[key]; }
      }
      for (var key in src_1405024) { dest_1405023[key] = src_1405024[key]; }
      result_1410219 = dest_1405023;
    
      break;
    case 18:
    case 17:
      if (!((ti_1405025.base == null))) {
      result_1410219 = nimCopy(dest_1405023, src_1405024, ti_1405025.base);
      }
      else {
      if ((ti_1405025.kind == 17)) {
      result_1410219 = (dest_1405023 === null || dest_1405023 === undefined) ? {m_type: ti_1405025} : dest_1405023;
      }
      else {
        result_1410219 = (dest_1405023 === null || dest_1405023 === undefined) ? {} : dest_1405023;
      }
      }
      nimCopyAux(result_1410219, src_1405024, ti_1405025.node);
      break;
    case 24:
    case 4:
    case 27:
    case 16:
            if (src_1405024 === null) {
        result_1410219 = null;
      }
      else {
        if (dest_1405023 === null || dest_1405023 === undefined) {
          dest_1405023 = new Array(src_1405024.length);
        }
        else {
          dest_1405023.length = src_1405024.length;
        }
        result_1410219 = dest_1405023;
        for (var i = 0; i < src_1405024.length; ++i) {
          result_1410219[i] = nimCopy(result_1410219[i], src_1405024[i], ti_1405025.base);
        }
      }
    
      break;
    case 28:
            if (src_1405024 !== null) {
        result_1410219 = src_1405024.slice(0);
      }
    
      break;
    default: 
      result_1410219 = src_1405024;
      break;
    }

  return result_1410219;

}
function cstrToNimstr(c_1390079) {
      var ln = c_1390079.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_1390079.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_1390079.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
function toJSStr(s_1390096) {
                    var Tmp5;
            var Tmp7;

  var result_1390097 = null;

    var res_1390170 = new_seq_1390128((s_1390096 != null ? s_1390096.length : 0));
    var i_1390172 = 0;
    var j_1390174 = 0;
    L1: do {
        L2: while (true) {
        if (!(i_1390172 < (s_1390096 != null ? s_1390096.length : 0))) break L2;
          var c_1390175 = s_1390096[i_1390172];
          if ((c_1390175 < 128)) {
          res_1390170[j_1390174] = String.fromCharCode(c_1390175);
          i_1390172 += 1;
          }
          else {
            var helper_1390198 = new_seq_1390128(0);
            L3: do {
                L4: while (true) {
                if (!true) break L4;
                  var code_1390199 = c_1390175.toString(16);
                  if (((code_1390199 != null ? code_1390199.length : 0) == 1)) {
                  if (helper_1390198 != null) { helper_1390198.push("%0"); } else { helper_1390198 = ["%0"]; };
                  }
                  else {
                  if (helper_1390198 != null) { helper_1390198.push("%"); } else { helper_1390198 = ["%"]; };
                  }
                  
                  if (helper_1390198 != null) { helper_1390198.push(code_1390199); } else { helper_1390198 = [code_1390199]; };
                  i_1390172 += 1;
                    if (((s_1390096 != null ? s_1390096.length : 0) <= i_1390172)) Tmp5 = true; else {                      Tmp5 = (s_1390096[i_1390172] < 128);                    }                  if (Tmp5) {
                  break L3;
                  }
                  
                  c_1390175 = s_1390096[i_1390172];
                }
            } while(false);
++excHandler;
            Tmp7 = framePtr;
            try {
            res_1390170[j_1390174] = decodeURIComponent(helper_1390198.join(""));
--excHandler;
} catch (EXC) {
 var prevJSError = lastJSError;
 lastJSError = EXC;
 --excHandler;
            framePtr = Tmp7;
            res_1390170[j_1390174] = helper_1390198.join("");
            lastJSError = prevJSError;
            } finally {
            framePtr = Tmp7;
            }
          }
          
          j_1390174 += 1;
        }
    } while(false);
    if (res_1390170 === null) res_1390170 = [];
               if (res_1390170.length < j_1390174) { for (var i=res_1390170.length;i<j_1390174;++i) res_1390170.push(null); }
               else { res_1390170.length = j_1390174; };
    result_1390097 = res_1390170.join("");

  return result_1390097;

}
function raiseException(e_1355218, ename_1355219) {
    e_1355218.name = ename_1355219;
    if ((excHandler == 0)) {
    unhandledException(e_1355218);
    }
    
    e_1355218.trace = nimCopy(null, raw_write_stack_trace_1345059(), NTI1166014);
    throw e_1355218;

  
}
function subInt(a_1395421, b_1395422) {
        var result = a_1395421 - b_1395422;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

  
}
function chckIndx(i_1415086, a_1415087, b_1415088) {
      var Tmp1;

  var result_1415089 = 0;

  BeforeRet: do {
      if (!(a_1415087 <= i_1415086)) Tmp1 = false; else {        Tmp1 = (i_1415086 <= b_1415088);      }    if (Tmp1) {
    result_1415089 = i_1415086;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_1415086, a_1415087, b_1415088);
    }
    
  } while (false);

  return result_1415089;

}
function chckRange(i_1420016, a_1420017, b_1420018) {
      var Tmp1;

  var result_1420019 = 0;

  BeforeRet: do {
      if (!(a_1420017 <= i_1420016)) Tmp1 = false; else {        Tmp1 = (i_1420016 <= b_1420018);      }    if (Tmp1) {
    result_1420019 = i_1420016;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  } while (false);

  return result_1420019;

}
function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
function eqStrings(a_1395222, b_1395223) {
        if (a_1395222 == b_1395223) return true;
    if (a_1395222 === null && b_1395223.length == 0) return true;
    if (b_1395223 === null && a_1395222.length == 0) return true;
    if ((!a_1395222) || (!b_1395223)) return false;
    var alen = a_1395222.length;
    if (alen != b_1395223.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_1395222[i] != b_1395223[i]) return false;
    return true;
  

  
}
function addInt(a_1395403, b_1395404) {
        var result = a_1395403 + b_1395404;
    if (result > 2147483647 || result < -2147483648) raiseOverflow();
    return result;
  

  
}
var nim_program_result = 0;
var global_raise_hook_1307018 = [null];
var local_raise_hook_1307023 = [null];
var out_of_mem_hook_1307026 = [null];
var unhandled_exception_hook_1307031 = [null];
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var tag_stack_1796015 = [null];
var last_node_1796016 = [null];
var tag_name_1796017 = [null];
var event_1796018 = [null];
function add_1307042(x_1307045, x_1307045_Idx, y_1307046) {
          if (x_1307045[x_1307045_Idx] === null) { x_1307045[x_1307045_Idx] = []; }
      var off = x_1307045[x_1307045_Idx].length;
      x_1307045[x_1307045_Idx].length += y_1307046.length;
      for (var i = 0; i < y_1307046.length; ++i) {
        x_1307045[x_1307045_Idx][off+i] = y_1307046.charCodeAt(i);
      }
    

  
}
function is_fat_pointer_1400401(ti_1400403) {
  var result_1400404 = false;

  BeforeRet: do {
    result_1400404 = !((ConstSet1[ti_1400403.base.kind] != undefined));
    break BeforeRet;
  } while (false);

  return result_1400404;

}
function nimCopyAux(dest_1405028, src_1405029, n_1405031) {
    switch (n_1405031.kind) {
    case 0:
      break;
    case 1:
            dest_1405028[n_1405031.offset] = nimCopy(dest_1405028[n_1405031.offset], src_1405029[n_1405031.offset], n_1405031.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_1405031.sons.length; i++) {
      nimCopyAux(dest_1405028, src_1405029, n_1405031.sons[i]);
    }
    
      break;
    case 3:
            dest_1405028[n_1405031.offset] = nimCopy(dest_1405028[n_1405031.offset], src_1405029[n_1405031.offset], n_1405031.typ);
      for (var i = 0; i < n_1405031.sons.length; ++i) {
        nimCopyAux(dest_1405028, src_1405029, n_1405031.sons[i][1]);
      }
    
      break;
    }

  
}
function aux_write_stack_trace_1325038(f_1325040) {
          var Tmp3;

  var result_1325041 = [null];

    var it_1325049 = f_1325040;
    var i_1325051 = 0;
    var total_1325053 = 0;
    var temp_frames_1325060 = arrayConstr(64, {Field0: null, Field1: 0}, NTI1325043);
    L1: do {
        L2: while (true) {
          if (!!((it_1325049 == null))) Tmp3 = false; else {            Tmp3 = (i_1325051 <= 63);          }        if (!Tmp3) break L2;
          temp_frames_1325060[i_1325051].Field0 = it_1325049.procname;
          temp_frames_1325060[i_1325051].Field1 = it_1325049.line;
          i_1325051 += 1;
          total_1325053 += 1;
          it_1325049 = it_1325049.prev;
        }
    } while(false);
    L4: do {
        L5: while (true) {
        if (!!((it_1325049 == null))) break L5;
          total_1325053 += 1;
          it_1325049 = it_1325049.prev;
        }
    } while(false);
    result_1325041[0] = nimCopy(null, [], NTI1166014);
    if (!((total_1325053 == i_1325051))) {
    if (result_1325041[0] != null) { result_1325041[0] = (result_1325041[0]).concat(makeNimstrLit("(")); } else { result_1325041[0] = makeNimstrLit("("); };
    if (result_1325041[0] != null) { result_1325041[0] = (result_1325041[0]).concat(cstrToNimstr(((total_1325053 - i_1325051))+"")); } else { result_1325041[0] = cstrToNimstr(((total_1325053 - i_1325051))+"").slice(); };
    if (result_1325041[0] != null) { result_1325041[0] = (result_1325041[0]).concat(makeNimstrLit(" calls omitted) ...\x0A")); } else { result_1325041[0] = makeNimstrLit(" calls omitted) ...\x0A"); };
    }
    
    L6: do {
      var j_1340236 = 0;
      var colontmp__4235289 = 0;
      colontmp__4235289 = (i_1325051 - 1);
      var res_4235294 = colontmp__4235289;
      L7: do {
          L8: while (true) {
          if (!(0 <= res_4235294)) break L8;
            j_1340236 = res_4235294;
            add_1307042(result_1325041, 0, temp_frames_1325060[j_1340236].Field0);
            if ((0 < temp_frames_1325060[j_1340236].Field1)) {
            if (result_1325041[0] != null) { result_1325041[0] = (result_1325041[0]).concat(makeNimstrLit(", line: ")); } else { result_1325041[0] = makeNimstrLit(", line: "); };
            if (result_1325041[0] != null) { result_1325041[0] = (result_1325041[0]).concat(cstrToNimstr((temp_frames_1325060[j_1340236].Field1)+"")); } else { result_1325041[0] = cstrToNimstr((temp_frames_1325060[j_1340236].Field1)+"").slice(); };
            }
            
            if (result_1325041[0] != null) { result_1325041[0] = (result_1325041[0]).concat(makeNimstrLit("\x0A")); } else { result_1325041[0] = makeNimstrLit("\x0A"); };
            res_4235294 -= 1;
          }
      } while(false);
    } while(false);

  return result_1325041[0];

}
function raw_write_stack_trace_1345059() {
  var result_1345061 = null;

    if (!((framePtr == null))) {
    result_1345061 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A") || []).concat(aux_write_stack_trace_1325038(framePtr) || []), NTI1166014);
    }
    else {
      result_1345061 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI1166014);
    }
    

  return result_1345061;

}
function new_seq_1390128(len_1390131) {
  var result_1390133 = null;

  var F={procname:"newSeq.newSeq",prev:framePtr,filename:"system.nim",line:0};
  framePtr = F;
    F.line = 643;
    result_1390133 = new Array(len_1390131); for (var i=0;i<len_1390131;++i) {result_1390133[i]=null;}  framePtr = F.prev;

  return result_1390133;

}
function unhandledException(e_1350059) {
    var buf_1350060 = [[]];
    if (!(((e_1350059.message != null ? e_1350059.message.length : 0) == 0))) {
    if (buf_1350060[0] != null) { buf_1350060[0] = (buf_1350060[0]).concat(makeNimstrLit("Error: unhandled exception: ")); } else { buf_1350060[0] = makeNimstrLit("Error: unhandled exception: "); };
    if (buf_1350060[0] != null) { buf_1350060[0] = (buf_1350060[0]).concat(e_1350059.message); } else { buf_1350060[0] = e_1350059.message.slice(); };
    }
    else {
    if (buf_1350060[0] != null) { buf_1350060[0] = (buf_1350060[0]).concat(makeNimstrLit("Error: unhandled exception")); } else { buf_1350060[0] = makeNimstrLit("Error: unhandled exception"); };
    }
    
    if (buf_1350060[0] != null) { buf_1350060[0] = (buf_1350060[0]).concat(makeNimstrLit(" [")); } else { buf_1350060[0] = makeNimstrLit(" ["); };
    add_1307042(buf_1350060, 0, e_1350059.name);
    if (buf_1350060[0] != null) { buf_1350060[0] = (buf_1350060[0]).concat(makeNimstrLit("]\x0A")); } else { buf_1350060[0] = makeNimstrLit("]\x0A"); };
    if (buf_1350060[0] != null) { buf_1350060[0] = (buf_1350060[0]).concat(raw_write_stack_trace_1345059()); } else { buf_1350060[0] = raw_write_stack_trace_1345059().slice(); };
    var cbuf_1355201 = toJSStr(buf_1350060[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_1355201);
  }
  else {
    throw cbuf_1355201;
  }
  

  
}
function raiseOverflow() {
    raiseException({message: makeNimstrLit("over- or underflow"), parent: null, m_type: NTI1172037, name: null, trace: null, up: null}, "OverflowError");

  
}
function raiseIndexError(i_1375047, a_1375048, b_1375049) {
    var Tmp1;

    if ((b_1375049 < a_1375048)) {
    Tmp1 = makeNimstrLit("index out of bounds, the container is empty");
    }
    else {
    Tmp1 = (makeNimstrLit("index ") || []).concat(cstrToNimstr((i_1375047)+"") || [],makeNimstrLit(" not in ") || [],cstrToNimstr((a_1375048)+"") || [],makeNimstrLit(" .. ") || [],cstrToNimstr((b_1375049)+"") || []);
    }
    
    raiseException({message: nimCopy(null, Tmp1, NTI1166014), parent: null, m_type: NTI1172049, name: null, trace: null, up: null}, "IndexError");

  
}
function HEX5BHEX5D_1805005(s_1805010, i_1805011) {
  var result_1805013 = null;
  var result_1805013_Idx = 0;

  var F={procname:"[].[]",prev:framePtr,filename:"system.nim",line:0};
  framePtr = F;
    F.line = 2522;
    result_1805013 = s_1805010; result_1805013_Idx = chckIndx(subInt((s_1805010 != null ? s_1805010.length : 0), i_1805011), 0, (s_1805010 != null ? s_1805010.length : 0)+0-1)-0;
  framePtr = F.prev;

  return [result_1805013, result_1805013_Idx];

}
function add_node_1796082(node_1796084) {
    var Tmp1;

  var F={procname:"taggy.addNode",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    if ((0 < (tag_stack_1796015[0] != null ? tag_stack_1796015[0].length : 0))) {
    F.line = 20;
    (Tmp1 = HEX5BHEX5D_1805005(tag_stack_1796015[0], 1), Tmp1)[0][Tmp1[1]].appendChild(node_1796084);
    }
    
  framePtr = F.prev;

  
}
function open_tag_1805069(name_1805071) {
  var F={procname:"taggy.openTag",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 23;
    tag_name_1796017[0] = name_1805071;
    F.line = 24;
    var node_1805072 = document.createElement(name_1805071);
    F.line = 25;
    add_node_1796082(node_1805072);
    F.line = 26;
    if (tag_stack_1796015[0] != null) { tag_stack_1796015[0].push(node_1805072); } else { tag_stack_1796015[0] = [node_1805072]; };
  framePtr = F.prev;

  
}
function text_1805235(s_1805237) {
  var F={procname:"taggy.text",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 34;
    last_node_1796016[0] = document.createTextNode(s_1805237);
    F.line = 35;
    add_node_1796082(last_node_1796016[0]);
  framePtr = F.prev;

  
}
function raiseRangeError() {
    raiseException({message: makeNimstrLit("value out of range"), parent: null, m_type: NTI1172053, name: null, trace: null, up: null}, "RangeError");

  
}
function pop_1805110(s_1805115, s_1805115_Idx) {
  var result_1805116 = null;

  var F={procname:"pop.pop",prev:framePtr,filename:"system.nim",line:0};
  framePtr = F;
    F.line = 1779;
    var l_1805122 = subInt((s_1805115[s_1805115_Idx] != null ? s_1805115[s_1805115_Idx].length : 0), 1);
    F.line = 1784;
    result_1805116 = s_1805115[s_1805115_Idx][chckIndx(l_1805122, 0, (s_1805115[s_1805115_Idx] != null ? s_1805115[s_1805115_Idx].length : 0)+0-1)-0];
    F.line = 1785;
    if (s_1805115[s_1805115_Idx] === null) s_1805115[s_1805115_Idx] = [];
               if (s_1805115[s_1805115_Idx].length < chckRange(l_1805122, 0, 2147483647)) { for (var i=s_1805115[s_1805115_Idx].length;i<chckRange(l_1805122, 0, 2147483647);++i) s_1805115[s_1805115_Idx].push(null); }
               else { s_1805115[s_1805115_Idx].length = chckRange(l_1805122, 0, 2147483647); };
  framePtr = F.prev;

  return result_1805116;

}
function close_tag_1805108() {
  var F={procname:"taggy.closeTag",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 29;
    tag_name_1796017[0] = null;
    F.line = 30;
    last_node_1796016[0] = pop_1805110(tag_stack_1796015, 0);
  framePtr = F.prev;

  
}
function set_attribute_1805598(name_1805600, s_1805601) {
    var Tmp1;

  var F={procname:"taggy.setAttribute",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 164;
    var node_1810013 = (Tmp1 = HEX5BHEX5D_1805005(tag_stack_1796015[0], 1), Tmp1)[0][Tmp1[1]];
    F.line = 165;
    node_1810013.setAttribute(name_1805600, s_1805601);
  framePtr = F.prev;

  
}
function id_2870214(s_2870216) {
  var F={procname:"taggy.id",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 233;
    set_attribute_1805598("id", s_2870216);
  framePtr = F.prev;

  
}
function class_2190214(s_2190216) {
  var F={procname:"taggy.class",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 192;
    set_attribute_1805598("class", s_2190216);
  framePtr = F.prev;

  
}
function set_style_4010477(name_4010479, s_4010480) {
    var Tmp1;

  var F={procname:"taggy.setStyle",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 400;
    var node_4015013 = (Tmp1 = HEX5BHEX5D_1805005(tag_stack_1796015[0], 1), Tmp1)[0][Tmp1[1]];
    F.line = 401;
    node_4015013.style[name_4010479] =s_4010480;
  framePtr = F.prev;

  
}
function color_4016019(s_4016021) {
  var F={procname:"taggy.color",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 465;
    set_style_4010477("color", toJSStr(s_4016021));
  framePtr = F.prev;

  
}
function handlerHEX22clickHEX22_4060001(this_eventHEX60gensym4055001_4060003) {
  var F={procname:"example.handler\"click\"",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 305;
    event_1796018[0] = this_eventHEX60gensym4055001_4060003;
    F.line = 14;
    rawEcho(makeNimstrLit("clicked"));
    F.line = 307;
    event_1796018[0] = null;
  framePtr = F.prev;

  
}
function sys_fatal_1267618(message_1267622) {
  var F={procname:"sysFatal.sysFatal",prev:framePtr,filename:"fatal.nim",line:0};
  framePtr = F;
    F.line = 49;
    raiseException({message: nimCopy(null, message_1267622, NTI1166014), m_type: NTI1172041, parent: null, name: null, trace: null, up: null}, "AssertionError");
  framePtr = F.prev;

  
}
function raise_assert_1267614(msg_1267616) {
  var F={procname:"assertions.raiseAssert",prev:framePtr,filename:"assertions.nim",line:0};
  framePtr = F;
    F.line = 22;
    sys_fatal_1267618(msg_1267616);
  framePtr = F.prev;

  
}
function failed_assert_impl_1267680(msg_1267682) {
  var F={procname:"assertions.failedAssertImpl",prev:framePtr,filename:"assertions.nim",line:0};
  framePtr = F;
    F.line = 29;
    raise_assert_1267614(msg_1267682);
  framePtr = F.prev;

  
}
  var Tmp2;
          var Tmp8;
L1: do {
  last_node_1796016[0] = null;
  open_tag_1805069("div");
  open_tag_1805069("h1");
  text_1805235("Basic example");
  close_tag_1805108();
  open_tag_1805069("div");
  id_2870214("main");
  class_2190214("round");
  color_4016019(makeNimstrLit("red"));
  text_1805235("hello world");
  (Tmp2 = HEX5BHEX5D_1805005(tag_stack_1796015[0], 1), Tmp2)[0][Tmp2[1]].addEventListener("click", handlerHEX22clickHEX22_4060001, false);
  close_tag_1805108();
  close_tag_1805108();
  if (!(((tag_stack_1796015[0] != null ? tag_stack_1796015[0].length : 0) == 0))) {
  failed_assert_impl_1267680(makeNimstrLit("C:\\p\\taggy\\src\\taggy.nim(14, 10) `tagStack.len == 0` "));
  }
  
  var node_4075201 = [last_node_1796016[0]];
  document.body.appendChild(node_4075201[0]);
} while(false);
L3: do {
  last_node_1796016[0] = null;
  open_tag_1805069("div");
  open_tag_1805069("h1");
  text_1805235("Just a text node (not a tag)");
  close_tag_1805108();
  text_1805235("hey how are you?");
  close_tag_1805108();
  if (!(((tag_stack_1796015[0] != null ? tag_stack_1796015[0].length : 0) == 0))) {
  failed_assert_impl_1267680(makeNimstrLit("C:\\p\\taggy\\src\\taggy.nim(14, 10) `tagStack.len == 0` "));
  }
  
  var node_4110201 = [last_node_1796016[0]];
  document.body.appendChild(node_4110201[0]);
} while(false);
L4: do {
  last_node_1796016[0] = null;
  open_tag_1805069("div");
  open_tag_1805069("h1");
  text_1805235("Table with a for loop");
  close_tag_1805108();
  open_tag_1805069("table");
  open_tag_1805069("tr");
  open_tag_1805069("th");
  text_1805235("id");
  close_tag_1805108();
  open_tag_1805069("th");
  text_1805235("color");
  close_tag_1805108();
  open_tag_1805069("th");
  text_1805235("size");
  close_tag_1805108();
  close_tag_1805108();
  L5: do {
    var i_4185009 = [0];
    var i_4235281 = 0;
    L6: do {
        L7: while (true) {
        if (!(i_4235281 < 10)) break L7;
          i_4185009[0] = i_4235281;
          open_tag_1805069("tr");
          open_tag_1805069("td");
          text_1805235(toJSStr((makeNimstrLit("#") || []).concat(cstrToNimstr((i_4185009[0])+"") || [])));
          close_tag_1805108();
          open_tag_1805069("td");
          text_1805235(toJSStr((Tmp8 = [makeNimstrLit("red"), makeNimstrLit("blue"), makeNimstrLit("black")], Tmp8)[Math.trunc(i_4185009[0] % 3)]));
          close_tag_1805108();
          open_tag_1805069("td");
          text_1805235(toJSStr(cstrToNimstr(((i_4185009[0] * 10))+"")));
          close_tag_1805108();
          close_tag_1805108();
          i_4235281 += 1;
        }
    } while(false);
  } while(false);
  close_tag_1805108();
  close_tag_1805108();
  if (!(((tag_stack_1796015[0] != null ? tag_stack_1796015[0].length : 0) == 0))) {
  failed_assert_impl_1267680(makeNimstrLit("C:\\p\\taggy\\src\\taggy.nim(14, 10) `tagStack.len == 0` "));
  }
  
  var node_4235201 = [last_node_1796016[0]];
  document.body.appendChild(node_4235201[0]);
} while(false);
function register_element_4235315(name_4235317) {
  var F={procname:"example.registerElement",prev:framePtr,filename:"example.nim",line:0};
  framePtr = F;
    F.line = 42;
    class Tmp extends HTMLElement {}
    F.line = 43;
    window.customElements.define(name_4235317, Tmp)
  framePtr = F.prev;

  
}
function display_4016275(s_4016277) {
  var F={procname:"taggy.display",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 481;
    set_style_4010477("display", toJSStr(s_4016277));
  framePtr = F.prev;

  
}
function background_color_4015251(s_4015253) {
  var F={procname:"taggy.backgroundColor",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 417;
    set_style_4010477("backgroundColor", toJSStr(s_4015253));
  framePtr = F.prev;

  
}
function cursor_4016243(s_4016245) {
  var F={procname:"taggy.cursor",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 479;
    set_style_4010477("cursor", toJSStr(s_4016245));
  framePtr = F.prev;

  
}
function user_select_4017827(s_4017829) {
  var F={procname:"taggy.userSelect",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 578;
    set_style_4010477("userSelect", toJSStr(s_4017829));
  framePtr = F.prev;

  
}
function width_4325003(s_4325006) {
  var F={procname:"width.width",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 592;
    set_style_4010477("width", toJSStr((cstrToNimstr((s_4325006)+"") || []).concat(makeNimstrLit("px") || [])));
  framePtr = F.prev;

  
}
function height_4325022(s_4325025) {
  var F={procname:"height.height",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 591;
    set_style_4010477("height", toJSStr((cstrToNimstr((s_4325025)+"") || []).concat(makeNimstrLit("px") || [])));
  framePtr = F.prev;

  
}
function handlerHEX22clickHEX22_4335001(this_eventHEX60gensym4330001_4335003) {
  var F={procname:"example.handler\"click\"",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 305;
    event_1796018[0] = this_eventHEX60gensym4330001_4335003;
    F.line = 76;
    rawEcho(cstrToNimstr(event_1796018[0].target.id));
    F.line = 77;
    rawEcho(makeNimstrLit("clicked"));
    F.line = 307;
    event_1796018[0] = null;
  framePtr = F.prev;

  
}
function handlerHEX22mousemoveHEX22_4350001(this_eventHEX60gensym4345001_4350003) {
  var F={procname:"example.handler\"mousemove\"",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 305;
    event_1796018[0] = this_eventHEX60gensym4345001_4350003;
    F.line = 79;
    rawEcho(makeNimstrLit("hovering"));
    F.line = 307;
    event_1796018[0] = null;
  framePtr = F.prev;

  
}
function find_1825016(a_1825020, item_1825021) {
  var result_1825022 = 0;

  var F={procname:"find.find",prev:framePtr,filename:"system.nim",line:0};
  framePtr = F;
  BeforeRet: do {
    L1: do {
      F.line = 1751;
      var i_1825028 = null;
      F.line = 3;
      var i_4620225 = 0;
      L2: do {
        F.line = 4;
          L3: while (true) {
          if (!(i_4620225 < (a_1825020 != null ? a_1825020.length : 0))) break L3;
            F.line = 1751;
            i_1825028 = a_1825020[chckIndx(i_4620225, 0, (a_1825020 != null ? a_1825020.length : 0)+0-1)-0];
            if (eqStrings(i_1825028, item_1825021)) {
            F.line = 1752;
            break BeforeRet;
            }
            
            F.line = 1753;
            result_1825022 = addInt(result_1825022, 1);
            F.line = 6;
            i_4620225 = addInt(i_4620225, 1);
          }
      } while(false);
    } while(false);
    F.line = 1754;
    result_1825022 = -1;
  } while (false);
  framePtr = F.prev;

  return result_1825022;

}
function contains_1825009(a_1825013, item_1825014) {
  var result_1825015 = false;

  var F={procname:"contains.contains",prev:framePtr,filename:"system.nim",line:0};
  framePtr = F;
  BeforeRet: do {
    F.line = 1768;
    result_1825015 = (0 <= find_1825016(a_1825013, item_1825014));
    break BeforeRet;
  } while (false);
  framePtr = F.prev;

  return result_1825015;

}
function ttype_3910246(s_3910248) {
  var F={procname:"taggy.ttype",prev:framePtr,filename:"taggy.nim",line:0};
  framePtr = F;
    F.line = 294;
    set_attribute_1805598("type", s_3910248);
    if (!(contains_1825009([makeNimstrLit("button"), makeNimstrLit("input"), makeNimstrLit("command"), makeNimstrLit("embed"), makeNimstrLit("object"), makeNimstrLit("script"), makeNimstrLit("source"), makeNimstrLit("style"), makeNimstrLit("menu")], cstrToNimstr(tag_name_1796017[0])))) {
    F.line = 294;
    failed_assert_impl_1267680(makeNimstrLit("C:\\p\\taggy\\src\\taggy.nim(294, 64) `$tagName in\x0A    [\"button\", \"input\", \"command\", \"embed\", \"object\", \"script\", \"source\", \"style\",\x0A     \"menu\"]` "));
    }
    
  framePtr = F.prev;

  
}
  var Tmp7;
  var Tmp8;
L2: do {
  register_element_4235315("area-list");
  register_element_4235315("area-wrapper");
  last_node_1796016[0] = null;
  open_tag_1805069("div");
  open_tag_1805069("h1");
  text_1805235("Custom HTML elements.");
  close_tag_1805108();
  open_tag_1805069("area-list");
  display_4016275(makeNimstrLit("block"));
  L3: do {
    var i_4270009 = [0];
    var i_4620217 = 0;
    L4: do {
        L5: while (true) {
        if (!(i_4620217 < 10)) break L5;
          i_4270009[0] = i_4620217;
          open_tag_1805069("area-wrapper");
          display_4016275(makeNimstrLit("block"));
          text_1805235(toJSStr((makeNimstrLit("area:") || []).concat(cstrToNimstr((i_4270009[0])+"") || [])));
          close_tag_1805108();
          i_4620217 += 1;
        }
    } while(false);
  } while(false);
  close_tag_1805108();
  close_tag_1805108();
  if (!(((tag_stack_1796015[0] != null ? tag_stack_1796015[0].length : 0) == 0))) {
  failed_assert_impl_1267680(makeNimstrLit("C:\\p\\taggy\\src\\taggy.nim(14, 10) `tagStack.len == 0` "));
  }
  
  var node_4290201 = [last_node_1796016[0]];
  document.body.appendChild(node_4290201[0]);
} while(false);
L6: do {
  last_node_1796016[0] = null;
  open_tag_1805069("div");
  open_tag_1805069("h1");
  text_1805235("Hover/clicking example.");
  close_tag_1805108();
  open_tag_1805069("div");
  id_2870214("hover-clicking-div");
  background_color_4015251(makeNimstrLit("red"));
  cursor_4016243(makeNimstrLit("pointer"));
  user_select_4017827(makeNimstrLit("none"));
  width_4325003(100);
  height_4325022(100);
  (Tmp7 = HEX5BHEX5D_1805005(tag_stack_1796015[0], 1), Tmp7)[0][Tmp7[1]].addEventListener("click", handlerHEX22clickHEX22_4335001, false);
  (Tmp8 = HEX5BHEX5D_1805005(tag_stack_1796015[0], 1), Tmp8)[0][Tmp8[1]].addEventListener("mousemove", handlerHEX22mousemoveHEX22_4350001, false);
  close_tag_1805108();
  close_tag_1805108();
  if (!(((tag_stack_1796015[0] != null ? tag_stack_1796015[0].length : 0) == 0))) {
  failed_assert_impl_1267680(makeNimstrLit("C:\\p\\taggy\\src\\taggy.nim(14, 10) `tagStack.len == 0` "));
  }
  
  var node_4365201 = [last_node_1796016[0]];
  document.body.appendChild(node_4365201[0]);
} while(false);
L9: do {
  last_node_1796016[0] = null;
  open_tag_1805069("div");
  open_tag_1805069("h1");
  text_1805235("Inputs example.");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("button");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("checkbox");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("color");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("date");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("datetime-local");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("email");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("file");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("hidden");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("image");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("month");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("number");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("password");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("radio");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("range");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("reset");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("search");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("submit");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("tel");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("text");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("time");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("url");
  close_tag_1805108();
  open_tag_1805069("input");
  ttype_3910246("week");
  close_tag_1805108();
  close_tag_1805108();
  if (!(((tag_stack_1796015[0] != null ? tag_stack_1796015[0].length : 0) == 0))) {
  failed_assert_impl_1267680(makeNimstrLit("C:\\p\\taggy\\src\\taggy.nim(14, 10) `tagStack.len == 0` "));
  }
  
  var node_4620201 = [last_node_1796016[0]];
  document.body.appendChild(node_4620201[0]);
} while(false);
